### ISSUE TITLE
Slight bug on headerbar, ignore headerbar custom color. GTK2 apps ignore custom titlebar color.

### ISSUE THREAD

**Issue by Trikenstein** [vinceliuice/Qogir-theme#206]
Installed on 2021-11-22

```
./install.sh -d ~/.themes -t manjaro -c dark --tweaks square 
```

Then added this at the bottom of  `~/.themes/Qogir-manjaro-dark/gtk-3.0/gtk.css` to customize titlebar color

```css
.titlebar, headerbar {
  background-color: #29a289;
}
.titlebar:backdrop, headerbar:backdrop {
  background-color: #104037;
}
```

Screenshot shows Gnome Tweaks app left panel still ignore the headerbar color.

Not shown in the screenshot: The titlebar in GTK2 apps is insensitive to the custom colors made above (titlebar remains dark gray)

![Qogir_ManjaroDark_withCustomTitlebarColor](https://user-images.githubusercontent.com/72353094/142804748-980b86bd-75fc-452a-83f1-f8ce9a5d5796.png)
