### ISSUE TITLE
Feature Request: Add a "Full Width Panel" variant to all your themes

### ISSUE THREAD

**Issue by arjpar** [vinceliuice/Qogir-theme#249]
This is very trivial to implement. If I'm correct, all it requires is the following change to `gnome-shell.css`:
```css
#panelBox {
  padding: 0;
}
```
