### ISSUE TITLE
Firefox titlebuttons not centered

### ISSUE THREAD

**Issue by horca** [vinceliuice/Qogir-theme#37]
Hi vinceliuice, really great job with the theme. Square variant has become my go to theme. But there is a small issue that just keeps on bothering me. The title buttons in Firefox are not centered
![screenshot from 2019-02-04 18-59-30](https://user-images.githubusercontent.com/15280930/52224260-dafa5880-28a7-11e9-9cad-32a3faa65825.png)
Close button is slightly centered slightly to the right and minimize button is centered slightly to the left.

**Comment by migalmoreno** [comment]
I too had this problem for a long time but found a working solution. To solve the alignment of the buttons, you can tweak the styles from line 4731 to 4753 in the `gtk.css` (I'm using the Qogir-win-dark variant). Then, I realized the images used for the button icons are too small for Firefox's default tab toolbar height, so in order to fit them nicely you need to resize the tab toolbar height to 30px. 

To to this, you need to add a `userChrome.css` in `~/.mozilla/firefox/{your_profile}/chrome/` (I'm on Linux)
For the tab toolbar itself:
```css
#TabsToolbar {
	max-height: 30px !important;
	min-height: 30px !important;
}
```
If you want your tabs to take the whole new height:
```css
.tabbrowser-tab {
  min-height: 30px !important;
  max-height: 30px !important;
  vertical-align: top !important;
  -moz-box-sizing: border-box !important;
  border: none !important;
}
```
And to change the default position of the titlebar buttons:
```css
.titlebar-buttonbox-container {
	margin-right: -4px !important;
}
```

Result:
![Screenshot from 2019-05-09 11-18-54](https://user-images.githubusercontent.com/41931001/57446312-51627a00-724c-11e9-8bd6-c3713a7629ca.png)
