### ISSUE TITLE
User icon not matching size.

### ISSUE THREAD

**Issue by jolupa** [vinceliuice/Qogir-theme#56]
Hi.
Where can I change the size of the user icon? Is not matching the same size from the other icons and I can't find any reference in the scss file...
The problem is this:
![image](https://user-images.githubusercontent.com/3421696/56538834-78d6f880-6564-11e9-95f7-84af601ee8b5.png)
Thanks!

**Comment by filipkemuel** [comment]
What GTK/Gnome version do you have?
The icon looks perfect for me on Gnome 3.32
The size is set in:  _sass/gnome-shell/_common.scss

```CSS
// a little unstructured mess:
.system-switch-user-submenu-icon.user-icon {
  icon-size: 20px;
  padding: 0 2px;
}

.system-switch-user-submenu-icon.default-icon {
  icon-size: 16px;
  padding: 0 4px;
}

.system-switch-user-submenu-icon {
  icon-size: 16px;
  padding: 0 4px;
}
```
On my system if i change `.system-switch-user-submenu-icon` i change the size of my user-icon.
However I think the two others are for older shell versions.
