### ISSUE TITLE
gnome-shell.css for Gnome 3.34

### ISSUE THREAD

**Issue by zeten30** [vinceliuice/Qogir-theme#86]
gnome-shell.css needs update for Gnome 3.34. See https://gitlab.gnome.org/GNOME/gnome-shell/commit/a78527050ada988f30f00adaf8a9a395b381b8a1?merge_request_iid=110

Otherwise, you may experience this https://github.com/ubuntu/yaru/issues/1434

```css
-  #searchResultsBin {
-    max-width: 1000px;
-  }

  #searchResultsContent {
+  max-width: 1000px;
    padding-left: 20px;

```
